Replace bump script with bump version workflow
opensafely-actions/cohort-report pull request #60
Opened 2021-12-17 17:55 UTC by iaindillingham

This replaces a bump script, which calls bump2version, with a bump
version workflow that is triggered by a conventional commit message. The
workflow makes releasing far less error-prone and ensures that releases,
and their corresponding changes, are much closer in the Git log.

You'll notice that the workflow is slightly different to other
OpenSAFELY workflows that use github-tag-action. This is because a new
version is not only used to tag a commit; it is also used to bump
instances of the old version within the repository. Why?

In the case of *cohortreport/VERSION*, this is because we don't want to
shell-out to Git to make the version available to the client. (You may
ask why we want to make the version available to the client; I'm afraid
I don't know the answer.)

More importantly, in the case of *README.md*, this is because we display
this file in <https://actions.opensafely.org/>. Users copy-and-paste the
*project.yaml* extract into their own studies; we want them to paste the
latest version. However, to encourage reproducibility, don't want to tag
a `latest` version. #45 is an example of when a hard-coded -- and, as it
happens, incorrect -- version has tripped up a researcher.

2021-12-18 11:17 UTC, madwort requested changes
looks good, but some nitpicks!

2021-12-18 11:17 UTC, madwort commented on .github/workflows/bump_version.yaml
> +          sed -i 's/[0-9]*\.[0-9]*\.[0-9]*/${{ needs.determine-new-version.outputs.new_version }}/g' README.md
should this regex be `/[0-9]*?\.[0-9]*?\.[0-9]*?/` for safety?

2021-12-18 11:17 UTC, madwort commented on .github/workflows/bump_version.yaml
> +      - "main"
good, this is correct, I think my other PR was incorrect

2021-12-18 11:17 UTC, madwort commented on .github/workflows/bump_version.yaml
> +          sed -i 's/[0-9]*\.[0-9]*\.[0-9]*/${{ needs.determine-new-version.outputs.new_version }}/g' README.md
Also, I currently get two matches if I run this regex on the repo? 
```
tom@MadBook3 cohort-report % grep '[0-9]*\.[0-9]*\.[0-9]*' README.md
    run: cohort-report:v2.1.0 output/input.csv
In this case, the specific input file is *output/input.csv* and the specific version of cohortreport is v1.0.0.
```
why not use `{{ needs.determine-new-version.outputs.previous_version }}`?

2021-12-18 11:17 UTC, madwort commented on .github/workflows/bump_version.yaml
> +          git commit -m '${{ needs.determine-new-version.outputs.commit_message }}'
do you know if this commit will be signed / Verified?

2021-12-20 10:47 UTC, iaindillingham commented on .github/workflows/bump_version.yaml
> +          sed -i 's/[0-9]*\.[0-9]*\.[0-9]*/${{ needs.determine-new-version.outputs.new_version }}/g' README.md
Actually, I think the regex should be `/[0-9]+?\.[0-9]+?\.[0-9]+?/`, for even more safety. (This requires passing `-E` to `sed` for extended regular expressions.)

I'm reluctant to use `${{ needs.determine-new-version.outputs.previous_version }}` instead of the regex because the target files -- *cohortreport/VERSION* and *README.md* -- may not contain the correct version strings; this may happen when a user mistakenly edits them. I think this workflow should correct these version strings, keeping the version strings in these files consistent with the version strings in the commit message and the tag message.

As an example, the current version of cohort-report is `2.1.0`. However, *README.md* contains `2.1.0` and `1.0.0`. Running this workflow would correct this discrepancy.

2021-12-20 10:49 UTC, iaindillingham commented on .github/workflows/bump_version.yaml
> +          sed -i 's/[0-9]*\.[0-9]*\.[0-9]*/${{ needs.determine-new-version.outputs.new_version }}/g' README.md
See `c9615fe`

2021-12-20 11:40 UTC, iaindillingham commented on .github/workflows/bump_version.yaml
> +          git commit -m '${{ needs.determine-new-version.outputs.commit_message }}'
I took the approach described in the [*Push a commit using the built-in token*](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token) scenario in the `actions/checkout` docs. Unfortunately, this approach doesn't sign the tagged commit. I've [forked the repo](https://github.com/iaindillingham/cohort-report) and pushed a conventional commit (the trigger commit) to `master`. You'll notice that the tagged commit isn't signed.

Based on my reading of actions/runner#667, I think that signing the tagged commit would require an action to import a GPG key (e.g. https://github.com/crazy-max/ghaction-import-gpg). Would you suggest adding such an action?

2022-01-12 10:21 UTC, madwort commented on .github/workflows/bump_version.yaml
> +          sed -i 's/[0-9]*\.[0-9]*\.[0-9]*/${{ needs.determine-new-version.outputs.new_version }}/g' README.md
Ok that sounds good. It's still a little magical for my taste (e.g. if someone added an unrelated comment to the readme like "do not use my_dependency 7.23.46 it's broken" it would also be changed), but very happy to cross that bridge if/when it happens (it won't).

2022-01-12 11:09 UTC, madwort commented on .github/workflows/bump_version.yaml
> +          git commit -m '${{ needs.determine-new-version.outputs.commit_message }}'
thanks @iaindillingham - been pondering this and our [general conclusion](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1641984037109000) is that we're not sure how meaningful this kind of signing would be - I propose merging the PR as-is and filing an issue on this repo that these commits are not signed, wdyt?

2022-01-12 11:15 UTC, iaindillingham commented on .github/workflows/bump_version.yaml
> +          git commit -m '${{ needs.determine-new-version.outputs.commit_message }}'
Sounds good to me!

2022-01-12 11:16 UTC, iaindillingham commented on .github/workflows/bump_version.yaml
> +          sed -i 's/[0-9]*\.[0-9]*\.[0-9]*/${{ needs.determine-new-version.outputs.new_version }}/g' README.md
That's a limitation, but I'd also prefer to cross that bridge when we come to it.

2022-01-12 11:18 UTC, madwort approved these changes

2022-01-12 11:19 UTC, merged